set(formula "\\frac{1}{2}")
execute_process(COMMAND "${EXE}" --backend "${formula}" RESULT_VARIABLE code OUTPUT_VARIABLE rendered ERROR_VARIABLE err)
if(NOT code EQUAL 0 OR NOT err STREQUAL "" OR NOT rendered MATCHES "─" OR NOT rendered MATCHES "1" OR NOT rendered MATCHES "2")
  message(FATAL_ERROR "backend rendering failed: ${code}: ${rendered} ${err}")
endif()
string(ASCII 27 esc)
if(rendered MATCHES "${esc}" OR rendered MATCHES "Result|Exact|OverCalc|Input|Pretty")
  message(FATAL_ERROR "backend output contains decorations: ${rendered}")
endif()
if(NOT rendered MATCHES "\n$")
  message(FATAL_ERROR "backend output lacks final newline")
endif()
set(input "${CMAKE_CURRENT_BINARY_DIR}/backend-input.txt")
file(WRITE "${input}" "${formula}")
foreach(mode default stdin file)
  if(mode STREQUAL "file")
    execute_process(COMMAND "${EXE}" --backend --file "${input}" RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err)
  elseif(mode STREQUAL "stdin")
    execute_process(COMMAND "${EXE}" --backend --stdin INPUT_FILE "${input}" RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err)
  else()
    execute_process(COMMAND "${EXE}" --backend INPUT_FILE "${input}" RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err)
  endif()
  if(NOT code EQUAL 0 OR NOT out STREQUAL rendered OR NOT err STREQUAL "")
    message(FATAL_ERROR "${mode} backend input differs: ${out} ${err}")
  endif()
endforeach()
execute_process(COMMAND "${EXE}" --backend "\\frac{1}{0}" RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT code EQUAL 0 OR NOT err STREQUAL "")
  message(FATAL_ERROR "backend must render without evaluation: ${err}")
endif()
execute_process(COMMAND "${EXE}" --backend "\\frac{1}{" RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT code EQUAL 1 OR NOT out STREQUAL "" OR err STREQUAL "")
  message(FATAL_ERROR "invalid input should fail with stderr only: ${code} ${out} ${err}")
endif()
foreach(flag --json --tui --steps --ascii --batch --timing)
  execute_process(COMMAND "${EXE}" --backend "${flag}" "2+2" RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(NOT code EQUAL 2 OR NOT out STREQUAL "")
    message(FATAL_ERROR "conflicting ${flag} accepted: ${code} ${out}")
  endif()
endforeach()
